### PR TITLE
Updated WebMachine Template for 21th Century

### PR DESCRIPTION
**Pull request by joedevivo**
No more 1990's WebMachine apps

### CODE REVIEW

**Comment by joedevivo** [comment]
Ye Olde Web Engine

**Comment by seancribbs** [comment]
Steam Powered

**Comment by bookshelfdave** [comment]
review all templates

**Comment by joedevivo** [comment]
:fish:

**Comment by vinoski** [comment]
:+1: fd3070f

**Comment by seancribbs** [comment]
@borshop merge

**Pull request merged**
