### PR TITLE
Adding type/spec info to wm_reqdata

### PR DESCRIPTION
**Pull request by seancribbs**
Rebased from #130.

### CODE REVIEW

**Comment by seancribbs** [comment]
@vinoski This is expected to be broken, making `wrq:wm_reqdata()` opaque opened Pandora's box.

**Comment by joedevivo** [comment]
@seancribbs this got closed when I deleted `develop`. Not sure if we want to pick this up where you left off or not.

**Comment by seancribbs** [comment]
Keep it closed, I think it needs to be redone.

**Comment by joedevivo** [comment]
yeah! it will probably get easier as the abstraction from mochiweb goes along too

**Pull request closed without merging**
