### PR TITLE
resolving critical bug

### PR DESCRIPTION
**Pull request by jrwest**
With the quip

### CODE REVIEW

**Comment by argv0** [comment]
+1

**Comment by jaredmorrow** [comment]
+1

**Comment by cmeiklejohn** [comment]
:+1:

**Comment by beerriot** [comment]
+1

**Comment by Vagabond** [comment]
+1

**Comment by rzezeski** [comment]
+1

**Comment by kuenishi** [comment]
+1

**Comment by cmeiklejohn** [comment]
@borshop +1 6e00596

**Comment by cmeiklejohn** [comment]
+1 6e00596

**Comment by justinsheehy** [comment]
+1

**Comment by joedevivo** [comment]
+1, never forget "no drinks"

**Comment by jrwest** [comment]
@borshop merge

**Comment by kellymclaughlin** [comment]
Excellent fix! Now we can cut a new branch with confidence.

**Pull request merged**
