### PR TITLE
Enhance rebar.config.script for dev only dependencies

### PR DESCRIPTION
**Pull request by seth**
ibrowse and meck are only used for testing and should not be imposed
as dependencies on projects using webmachine.

rebar.config.script is used to support a dev_only_deps key in
rebar.config. The mechanism is triggered by a marker file DEV_MODE
written to the top-level of the project directory. If found, the
dev_only_deps are merged into deps. The project's Makefile is modified
to create the DEV_MODE file. Those doing dev work on webmachine can
continue to run builds via standard make commands. Projects pulling in
a dep on webmachine via rebar will receive just the needed bits.

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
Functionally this seems fine, but what do you think about making the `DEV_MODE` file a hidden file?

**Comment by seth** [comment]
I'd be happy to adjust it if you prefer.

My initial thinking was to make it more obvious to someone working with the code.

In the "rebar improvement wrapper" concrete I opted for `$PROJ_DIR/.concrete/DEV_MODE`. concrete adds dev_only_deps, edown support to publish edoc to github, and standard make targets.
https://github.com/opscode/concrete

Anyhow, if you want to go with a hidden file and want me to adjust the patch, just tell me the name.

**Comment by kellymclaughlin** [comment]
I totally dropped the ball on this PR. I apologize for that,  but if you are still interested and want to just adjust `DEV_MODE` to be a hidden file then I'll go ahead and merge this in.

**Comment by seth** [comment]
Since rebar now creates a `.rebar/` directory, should we put DEV_MODE there or would you prefer $PROJ_DIR/.DEV_MODE?

**Comment by kellymclaughlin** [comment]
> Since rebar now creates a .rebar/ directory, should we put DEV_MODE there or would you prefer $PROJ_DIR/.DEV_MODE?

That sounds good. Webmachine still includes an old version of rebar, but I'll open a quick PR to update it before merging this in.

**Comment by kellymclaughlin** [comment]
I rebased this branch so it will merge cleanly and corrected a few issues with the OTP version checking in the `rebar.config.script` file. I also moved the `DEV_MODE` file to `.rebar`. As long as it passes the CI tests I'll get it merged in later today.

https://github.com/basho/webmachine/pull/228

**Comment by seth** [comment]
Great! Thanks. Sorry I meant to help with that, but it fell off my list.
Much appreciated!

**Comment by kellymclaughlin** [comment]
#228 is merged so closing this. Thanks again!

**Pull request closed without merging**
