### PR TITLE
update to newest version of mochiweb

### PR DESCRIPTION
**Pull request by djnym**
I was surprised to find that webmachine was so far behind because I've been running my local webmachine with updated mochiweb in production for many months.   This may be too big of a move for you, but if not, here's the patch.

### CODE REVIEW

**Comment by seancribbs** [comment]
@djnym This seems fine, can you rebase/resolve so that this merges cleanly?

**Comment by djnym** [comment]
Well, that's odd, I thought I did it correctly but seem to have gotten some documentation changes as well, not sure how that happened?  But they are probably benign.  I can figure out how to clean it up if you want.

**Comment by seancribbs** [comment]
Thanks @djnym!

**Comment by seancribbs** [comment]
:+1: 1c35a34

**Comment by seancribbs** [comment]
@borshop merge

**Pull request merged**
