### PR TITLE
support maps for Erlang 17.x  in webmachine_resource/escape_trace_data for 

### PR DESCRIPTION
**Pull request by sergium**

### CODE REVIEW

**Comment by sergium** [comment]
this fix allows wmtrace - to serialize\deserialize maps in the request-context

**Comment by joedevivo** [comment]
accidentally closed

**Comment by sergium** [comment]
no problem)

if you have any questions \ suggestions - just let me know (it's my first project with webmachine)

**Comment by beerriot** [comment]
LGTM. To test, I put an anonymous function in my resource's context. `wmtrace_resource` blows up with this before:

```erlang
{error,
    {error,
        {badmatch,{error,{855,erl_parse,["syntax error before: ","Fun"]}}},
```

But it successfully loads the trace with the escaped fun after:

```erlang
#{foo => bar,
       "myfun" =>
           {'WMTRACE_ESCAPED_FUN',
               [{module,dustoff_resource},
                {name,'-to_html/2-fun-0-'},
                {arity,0},
                {type,local}]},
```

Thanks!

**Comment by beerriot** [comment]
… and only now do I remember that this PR was targetted at the develop branch. I'll add this change to #313

**Pull request merged**
