### PR TITLE
Create CI github actions workflow

### PR DESCRIPTION
**Pull request by seancribbs**

### CODE REVIEW

**Comment by beerriot** [comment]
I've never used Github Actions, but this looks like a thing I want. Is it still good to go three years (sorry!) later? If so, let's add OTP 23, 24, 25, and merge. 👍🏻

**Comment by seancribbs** [comment]
Thanks @beerriot. Other things have changed since I made this, so I should probably be using the `erlef/setup-beam` action instead. I'll look into it tonight.

**Comment by fadushin** [comment]
Feel free to borrow/steal workflows out of https://github.com/atomvm/AtomVM/tree/master/.github/workflows

**Comment by seancribbs** [comment]
ohai @fadushin 😄

**Comment by seancribbs** [comment]
@beerriot Finally got all the versions working and the IPv6 tests as well.

**Review by beerriot — APPROVED** [review]
Woohoo! Let's merge!

**Pull request merged**
