### PR TITLE
Massive Update

### PR DESCRIPTION
**Pull request by joedevivo**
- rebar3
- moved demo app to webmachine-demo repo
- moved www to webmachine.github.io repo
- rebar3-template to new repo
- bye bye shell scripts

### CODE REVIEW

**Comment by joedevivo** [comment]
Here's the work I mentioned in #249

**Comment by tsloughter** [comment]
Nice!

**Comment by seancribbs** [comment]
So good. :+1:

**Comment by bookshelfdave** [comment]
any reason ibrowse can't be updated to `4.1.1`?

**Comment by joedevivo** [comment]
@metadave it was a test only dep and I was trying to move as little as possible here. No problem bumping it in the future tho.

**Comment by jadeallenx** [comment]
Great job! Thanks.

**Pull request merged**
