### PR TITLE
Run content_types_provided handlers for POST

### PR DESCRIPTION
**Pull request by Cy6erBr4in**
Run handlers returned by contect_types_provided/2 for POST requests as well. Before this change those handlers (if there're any) were run only for GET and HEAD requests.

This change is related to the issue #122.

### CODE REVIEW

**Comment by seancribbs** [comment]
:-1: The semantics of POST are not constrained enough to say it is related to the normal GET/HEAD/PUT flow and their responses. It would be better, in my opinion, to expose a means to negotiate the response type inside `process_post`.

**Comment by Cy6erBr4in** [comment]
well, OK, I agree this isn't the best solution, but currently the situation is bizarre: if a client sets an Accept header, and you don't implement content_types_provided/2 in your module, the request most likely will fail with 406 error. On the other hand if you implement content_types_provided/2, the handlers it returns will never be used for POST requests. Do you have any ideas for workarounds?

**Comment by seancribbs** [comment]
Tagging @justinsheehy

**Comment by vinoski** [comment]
Taking a fresh look at this, I believe @seancribbs has it correct. The code path in question under `decision(v3o18)` is clearly intended for `GET` and `HEAD`; it specifically checks for one of those methods and if present, proceeds to deal with etag generation along with `Last-Modified` and `Expires` headers, all of which would be pretty unusual for `POST` responses. This seems to mean that the `content_types_provided` handlers are intended to be invoked for `GET` and `HEAD` requests only, though I don't believe that's documented. Also, the `decision(v3o20)` implementation indicates that `process_post` should be setting a response body, so if you've written your `content_types_provided` handlers such that they can be used for methods other than just `GET` and `HEAD`, you could just have your  `process_post` code call the right handler directly.

**Comment by justinsheehy** [comment]
(sorry for missing the original long-ago tag)

I concur with @seancribbs and @vinoski on this.

@Cy6erBr4in: I agree that it's a little confusing, but I think that here we are dealing with a confusing aspect of HTTP itself.

The POST method is left intentionally so undefined that some of the constraints expected on other methods do not apply, so if you decide to handle a POST we pretty much just get out of the way. I would say that it might be equally or even more confusing to some people if we had some of those other handlers apply in that case, and thus only got halfway out of the way during a POST.

**Pull request closed without merging**
