### PR TITLE
IPv6 support 2015

### PR DESCRIPTION
**Pull request by joedevivo**
Rebased against develop version of @seth's PR (#180) from 2013

### CODE REVIEW

**Comment by seancribbs** [comment]
:+1: 41c1744

**Comment by seancribbs** [comment]
:+1: cd51020

**Comment by joedevivo** [comment]
sad trombone

**Comment by seancribbs** [comment]
:+1: f209285

once more, with feeling

**Comment by seancribbs** [comment]
@borshop merge

**Pull request merged**
