### PR TITLE
Guess text/css MIME type for .less files

### PR DESCRIPTION
**Pull request by bjnortier**
This is needed to avoid 406 errors when loading & parsing Less file in the browser

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
Can you elaborate on why `text/less` instead of `test/css`?

**Comment by bjnortier** [comment]
I got confused because my <link> tag was wrong - thanks for making me look again. It should be text/css. This works with text/css:

```
<link rel="stylesheet/less" href="/foo.less" type="text/css" media="screen" />
```

using the JS less parser

**Comment by kellymclaughlin** [comment]
Thanks, I'll merge this in.

**Comment by bjnortier** [comment]
Thanks

**Pull request merged**
