### PR TITLE
update ibrowse to 4.0.2

### PR DESCRIPTION
**Pull request by kuenishi**
Riak CS also uses ibrowse 4.0.2 via [erlcloud](https://github.com/basho/erlcloud) for testing. When [trying to update webmachine](https://github.com/basho/riak_cs/pull/890) it consequently depends on ibrowse 4.0.1, which conflicts against 4.0.2. This pull request updates dependency to 4.0.2, and relieves version requirement as well.

Note: this doesn't block Riak CS work but I'd be happy if this merged before CS 1.5.0 final goes out.

### CODE REVIEW

**Comment by seancribbs** [comment]
We need to be careful about this. Transitively dependent projects depend on specific versions of ibrowse. I'm not sure why (testing?) webmachine depends on ibrowse at all.

**Comment by kuenishi** [comment]
ibrowse is used in `decision_core_test:stream_content_md5/0` (actually it's not called from eunit, because it's broken), although it looks like not hard to replace with httpc. I'm also not sure why it should be ibrowse. Maybe I can try later.

I guess the only module which directly requires ibrowse in Riak is Yokozuna. Otherwise it's for test use - or even it should be in riak_test?

**Comment by seancribbs** [comment]
:+1: f99a63d

**Comment by seancribbs** [comment]
@borshop merge

**Pull request merged**
