### PR TITLE
change hash fns for R16B01 compat

### PR DESCRIPTION
**Pull request by cmeiklejohn**
Rebased #154.

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
:+1:

**Comment by evanmcc** [comment]
please revert, this change breaks R15 compatability.

**Comment by evanmcc** [comment]
hm.  maybe it doesn't?  that doesn't make any sense, it breaks KV and core.

**Comment by kellymclaughlin** [comment]
I don't know why it would break R15. I did some limited testing with R15 and it seemed fine in my tests.

**Comment by evanmcc** [comment]
core and kv both fail with function undefined errors on some of those
crypto hash functions.

Res: {exception,
         {'EXIT',
             {undef,
                 [{crypto,hash,

[md5,<<131,104,3,98,0,0,5,93,98,0,7,65,2,98,0,9,220,1>>],
                      []},
                  {hashtree,new_segment_store,2,
                      [{file,"src/hashtree.erl"},{line,472}]},
                  {hashtree,new,2,[{file,"src/hashtree.erl"},{line,215}]},
                  {eqc_statem,run_commands,2,
                      [{file,"../src/eqc_statem.erl"},{line,606}]},
                  {hashtree_eqc,'-prop_correct/0-fun-4-',1,
                      [{file,"test/hashtree_eqc.erl"},{line,182}]}]}}}

It could be that the webmachine tests don't exercise body hashing.

**Pull request merged**
