### PR TITLE
Move webmachine_logger.hrl to include directory.

### PR DESCRIPTION
**Pull request by djnym**
This makes it easy to provide your own custom logging.  If the .hrl is not
in the include you have to set up additional paths to be able to include it.

### CODE REVIEW

**Comment by PharkMillups** [comment]
Thanks for putting this together, Anthony. It's queued up for review. 

Mark

**Comment by djnym** [comment]
Any idea if this will be merged soon (or at least prior to next release of webmachine)?

**Comment by djnym** [comment]
Oops, hadn't realized I closed the request, I do still want this one to go through :).

**Comment by skeltoac** [comment]
My Riak project would benefit from this as well.

**Comment by jtuple** [comment]
Straightforward change. Verified that changes don't break Webmachine or Riak compilation, and standard tests still pass. Going to go ahead and merge this.

Sorry about 9 month delay. We've adopted new community pull-request policy that should ensure thinks get reviewed sooner and don't fall through the cracks. In any case, thanks for the contribution.

**Pull request merged**
