### PR TITLE
Increase line coverage of webmachine unit and integration tests. The

### PR DESCRIPTION
**Pull request by macshonle**
goal for this first round is to increase coverage of the decision core
of webmachine. For each node on the v3 HTTP activity diagram there are
one or more tests that reach that node.

There are tests to cover 406, 412, 401, 400, 301, 307, 304, 404, 201,
409, 303, 202, 200, 201, 410, 300, 500, 501, 403, 414, 415, 413,
including Vary headers, streaming bodies, MD5 sums.

Additionally, extra logging and archiving have been added to access
data on Travis CI.

Some of the previously existing tests have been fixed, as well as a
minor bug in webmachine itself.

### CODE REVIEW

**Comment by reiddraper** [comment]
All tests pass on a clean checkout, nice. I'll start going through the code asap.

**Comment by reiddraper** [comment]
Some testing TODO notes for myself:
- [x] Test branch in Riak CS
- [ ] Test branch in Riak

**Comment by reiddraper** [comment]
@mshonle I'm still (slowly) doing review on this, but any chance you could run all of the Riak riak_tests with a Riak build using this branch of WM?

**Comment by kellymclaughlin** [comment]
I fixed a failing test case and fixed some periodic failure with the `etag_test`. I'm :+1: to merge this.

**Pull request merged**
