### PR TITLE
Add request timing option for access logger

### PR DESCRIPTION
**Pull request by kellymclaughlin**
Add the ability to specify a boolean configuration parameter to the
webmachine_access_log_handler module to have it include request
duration reporting as part of its log output. The request durations
are reported in microseconds and this option is disabled by default so
that the current default behavior is maintained.

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
As an example of using this option, here is the log handler configuration from the provided demo app changed to use this option:

```
LogHandlers = [{webmachine_access_log_handler, ["priv/log", true]},
                   {webmachine_error_log_handler, ["priv/log"]}],
```

Here is some sample output:

```
127.0.0.1 - - [19/Aug/2014:15:11:47 -0600] "GET /demo HTTP/1.1" 200 51 "" "curl/7.37.1" 672
127.0.0.1 - - [19/Aug/2014:15:11:48 -0600] "GET /demo HTTP/1.1" 200 51 "" "curl/7.37.1" 912
127.0.0.1 - - [19/Aug/2014:15:11:49 -0600] "GET /demo HTTP/1.1" 200 51 "" "curl/7.37.1" 618
127.0.0.1 - - [19/Aug/2014:15:11:50 -0600] "GET /demo HTTP/1.1" 200 51 "" "curl/7.37.1" 947
127.0.0.1 - - [19/Aug/2014:15:11:51 -0600] "GET /demo HTTP/1.1" 200 51 "" "curl/7.37.1" 805
127.0.0.1 - - [19/Aug/2014:15:11:52 -0600] "GET /demo HTTP/1.1" 200 51 "" "curl/7.37.1" 654
127.0.0.1 - - [19/Aug/2014:15:11:53 -0600] "GET /demo HTTP/1.1" 200 51 "" "curl/7.37.1" 906
127.0.0.1 - - [19/Aug/2014:15:11:55 -0600] "GET /demo HTTP/1.1" 200 51 "" "curl/7.37.1" 693
```

**Comment by vinoski** [comment]
@borshop merge

**Comment by vinoski** [comment]
@borshop merge

**Comment by kellymclaughlin** [comment]
+1 d710cfe3ca3

**Comment by kellymclaughlin** [comment]
@djnym Thanks for the comment. I understand concern certainly. We do plan to make the next cut from `develop` a new major version and the `1.10` branch will remain unaffected. The state record duplication and leakage in `webmachine_log` made it difficult to do much logger module specialization and needed to be fixed. Hopefully the required modifications to any custom module will be minimal and prove to be a worthwhile investment of effort.

**Pull request merged**
