### PR TITLE
Various Media Range Params Fixes

### PR DESCRIPTION
**Pull request by jrwest**
This follows up on a bug originally adressed by this pull request https://github.com/basho/webmachine/pull/21 but that I don't think was ever completed from what I can tell (I haven't been able to find any other references and I was able to recreate the issues mentioned).

2 bug fixes and a minor "improvement":
- Fixes formatting of content types that contain parameters. Originally, this would cause webmachine to crash in certain cases
- fixing above caused webmachine to crash in v3o18 instead. this no longer occurs
- It was documented in `webmachine_util:choose_media_type/2` that atoms could be used as keys in the media-types params list, this is now supported.

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
How about a test case like this? (or even exactly this):

```
format_content_type_test() ->
    Types = ["audio/vnd.wave; codec=31",
             "Text/x-Okie; charset=iso-8859-1; declaration=\"<f950118.AEB0@XIson.com>\""],
    [?assertEqual(Type, format_content_type(
                          webmachine_util:media_type_to_detail(Type)))
     || Type <- Types],
    ?assertEqual(hd(Types), format_content_type("audio/vnd.wave", [{codec, "31"}])).
```

**Comment by kellymclaughlin** [comment]
I wondered if it should support the value of a parameter pair being an integer, but I do not see that it can ever be converted to an integer so I don't think it's worth it.

**Comment by jrwest** [comment]
added suggested test

**Comment by jrwest** [comment]
closing this PR in favor of #112 (same branch rebased on master)

**Pull request closed without merging**
