### PR TITLE
Avoid localtime to universaltime

### PR DESCRIPTION
**Pull request by shino**
httpd_util:rfc1123_date/1 uses internally erlang:localtime_to_universaltime/2
with 2nd argument of true. The function takes msec or tens of msec
depending on concurrency.

Usage of httpd_util:rfc1123_date/1 in webmachine_decision_core is
tuple style GMT -> tuple-style localtime -> RFC 1123 string (also GMT).
New utility function webmachine_util:rfc1123_date converts
tuple style GMT to RFC 1123 string directly.

### CODE REVIEW

**Comment by slfritchie** [comment]
Shino, would it be worth the effort (separate from this ticket) to submit a patch to the Erlang/OTP team to fix this time sucker?

**Comment by shino** [comment]
Maybe it's nice.
The function `erlang:localtime_to_universaltime/2` is BIF and I don't dig further. I am not good at C...
I guess `mktime` is ...

**Comment by kuenishi** [comment]
let's write `httpd_util:rfc1123_date2/1` with input universal time of format `{{Y,M,D},{HH,MM,SS}}` and send to erlang/otp :)

**Comment by kellymclaughlin** [comment]
Did you do measurements using `webmachine_util:rfc1123_date`? What sort of improvements did you see?

**Comment by shino** [comment]
Sorry that I forgot to mention benchmark result.

One measurement is by apache bench (concurrency 10).
Time per requests are:
- 26.5 msec at current master (d7f82fa)
- 1.7 msec at this PR branch

details > https://gist.github.com/shino/5975660

**Comment by shino** [comment]
Another micro benchmark

https://gist.github.com/shino/8e69f4cddecd196f1114
(`bmp/3` is utility function in my user_default > https://gist.github.com/shino/5963764 )

**Comment by kellymclaughlin** [comment]
> Another micro benchmark

Wow, that's compelling

**Comment by kellymclaughlin** [comment]
I've run the webmachine tests and also run all of the RiakCS tests using this branch with no problems. This looks good to me.

+1 to merge

**Pull request merged**
