### PR TITLE
Eliminate use of module_info to check whether a module exports a function

### PR DESCRIPTION
**Pull request by richcarl**
Calling module_info() is comparatively expensive and is best avoided.

### CODE REVIEW

**Review by seancribbs — APPROVED** [review]
👍  This looks good to me but I would like a second opinion.

**Comment by vinoski** [comment]
LGTM too.

**Comment by richcarl** [comment]
We did some profiling and found that some calls to module_info() in the system were standing out a bit. This was one of them. We were on a much older webmachine version though, so I had to forward port the change to upstream.

**Comment by richcarl** [comment]
Those test failures look weird. Are they expected to work in the github travis?

**Comment by beerriot** [comment]
If it's good enough for gen_server, it's good enough for me. If the module_loaded/ensure_loaded step runs into the same bottleneck, that could maybe be moved to webmachine_router:init and add_route, so it's not done on every request.

+1 thanks!

**Comment by richcarl** [comment]
Note that the call to erlang:module_loaded() is fast, and the code:ensure_loaded() path is taken at most once.

**Comment by richcarl** [comment]
What's your take on live code loading, btw? Leave old functions like new/4 around for a while to support upgrades, or skip such niceties?

**Comment by richcarl** [comment]
Does anybody fancy merging this, or do you want something changed first?

**Comment by seancribbs** [comment]
I'll yolo-merge it.

**Pull request merged**
