### PR TITLE
Read body when DELETE to keep alive connection

### PR DESCRIPTION
**Pull request by shino**
DELETE may have body and mochiweb will close socket because it's unsafe
to keep alive with remaining bytes.

### CODE REVIEW

**Comment by reiddraper** [comment]
I can confirm this fixes basho/riak_cs#521, but I have a couple questions:
1. What happens if the body is > 50MB?
2. Is that whole (potentially) 50MB body buffered in memory?
3. I don't think this would actually be useful, but this does prevent the resource author from reading a greater-than 50MB stream, as a stream body.

**Comment by shino** [comment]
Thanks for comments and mumble.

>    What happens if the body is > 50MB?

Changed to use streaming.

>    I don't think this would actually be useful, but this does prevent the resource author from reading a greater-than 50MB stream, as a stream body.

Moved flushing code after calling `resource_call`.

>    Is that whole (potentially) 50MB body buffered in memory?

Also changed not to keep bytes in memory.

If I missed the points discussed in mumble (I'm afraid it's probable),
could you please tell me?

**Comment by reiddraper** [comment]
(cc/ @kellymclaughlin)

I think this looks great. It fixes basho/riak_cs#521, and still works if I add a call to `wrq:req_body/1` in `delete_resource` of `riak_cs_wm_bucket_policy`. Pending Kelly taking a look too, I'm +1.

**Comment by kellymclaughlin** [comment]
I agree, +1 to merge

**Pull request merged**
