### PR TITLE
Additional R16B01 compatibility changes.

### PR DESCRIPTION
**Pull request by evanmcc**
change hash fns as R16B01 ads deprecation warnings that stop us from building with warnings as errors.

### CODE REVIEW

**Comment by kellymclaughlin** [comment]
:+1:

**Comment by cmeiklejohn** [comment]
:+1: as well, just ran into this myself.  What can we do to get this merged?

**Comment by kellymclaughlin** [comment]
> :+1: as well, just ran into this myself. What can we do to get this merged?

What do I have to do to get you into a merge today? I got this fine merge right here, it has all the bells and whistles. I'll even throw in `--no-ff` for free! This deal won't last so get it while you can!

**Comment by cmeiklejohn** [comment]
Closing in favor of #155.

**Pull request closed without merging**
