### PR TITLE
Allow multiple webmachine instance to run in the same app

### PR DESCRIPTION
**Pull request by kellymclaughlin**
Changes to allow multiple instances of webmachine to coexist within
the same erlang application. The instances can use distinct dispatch
tables and be configured to listen on different IP addresses or port
numbers. 

The current behavior is maintained as the default, but may be
overridden by setting `default_router` to `false` in the application
environment and starting named router processes from the application
supervisor prior to calling `webmachine_mochiweb:start`.

The key is to provide a distinct name for each router using `webmachine:start_link/1` and to include that name as the value for the `name` key in the `Config` passed to `webmachine_mochiweb:start/1`.

### CODE REVIEW

**Comment by reiddraper** [comment]
+1! yay!

**Comment by cmeiklejohn** [comment]
This is fantastic!

**Comment by reiddraper** [comment]
@seancribbs was musing about a potentially better way to achieve this, as it seems to have broken Riak master. Mentioning him in case he wants to put some thoughts on the PR here.

**Comment by seancribbs** [comment]
@reiddraper Actually opened a PR for it already, #128.

**Pull request merged**
